### ISSUE TITLE
Optional imports

### ISSUE THREAD

**Issue by manolomartinez** [signalling-games-org/evoke#52]
We should perhaps decide which external libraries are non-optional (`numpy`, `matplotlib`, `scipy`, I think) and which ones are optional. For the optional ones we should do something like:

``` python
try:
    import optional_lib
    optional_lib_exists = True
except ModuleNotFoundError:
    optional_lib_exists = False
```

We would then check for that flag wherever the optional import would be used. I reckon `gambit`, `ternary`, and perhaps others should be optional.

**Comment by stephenfmann** [comment]
`pygambit` is taking a very long time to install on the hosted runtime for the Google Colab document, so I would make that a priority.

**Comment by manolomartinez** [comment]
So this is now done, right?

**Comment by stephenfmann** [comment]
For pygambit yes, so this can be closed.
