### ISSUE TITLE
Can we delete `MANIFEST.in`?

### ISSUE THREAD

**Issue by stephenfmann** [signalling-games-org/evoke#70]
It looks like old functionality that isn't doing anything any more.

**Comment by manolomartinez** [comment]
`MANIFEST.in` was supposed to make sure that `README` and `COPYING` files were added to the python package. Is there a better way to do this now?

By the way, `COPYING` is the name for the license text file [recommended by the Free Software Foundation](https://www.gnu.org/licenses/gpl-howto.html).

**Comment by stephenfmann** [comment]
From the fact that `MANIFEST.in` contains the line `recursive-include skyrms *`, I inferred it was redundant, since we no longer have a subdirectory called `skyrms`. I might be wrong, but the fact that the package is building successfully with the subdirectory named `evoke` suggests to me that everything is fine without it. (Though `MANIFEST` is including `setup.py`, which contains the line `packages=["evoke"]`, so maybe it's required for that.)

On the `COPYING`/`LICENSE` thing, we were [asked by a reviewer for JOSS to change it](https://github.com/openjournals/joss-reviews/issues/6703#issuecomment-2162994909), so I changed it. I don't mind if we change it back; I guess it being recommended by the Free Software Foundation should be a good enough argument in the review.

**Comment by manolomartinez** [comment]
When we install evoke with pip, do we get a copy of the license and the README? I was trying to do it right now, but my current python version is higher than what evoke allows (which should probably be changed?).

And sure, I'm happy with `LICENSE`, just wanted to let you know where the other thing came from :)

**Comment by stephenfmann** [comment]
I just installed in a virtual environment with python 3.9 and there is no README or license file in the site-packages (see image); I guess that means something isn't working that should be:

![image](https://github.com/user-attachments/assets/38aca8a0-8209-4fb6-a99c-f15b6c2cb11d)

I will test with python 3.12 and update the requirements if all is well.

I'll leave the license file as `LICENSE` just because that's what the reviewer expected and I guess what others will expect.

**Comment by stephenfmann** [comment]
Update: the following appears in a separate folder, but still no README:

![image](https://github.com/user-attachments/assets/9b69a57e-da35-4d1d-b90d-2084bec658e1)

**Comment by manolomartinez** [comment]
This is what `MANIFEST.in` was supposed to do... I'll look into it.

**Comment by stephenfmann** [comment]
The [poetry documentation](https://python-poetry.org/docs/basic-usage#project-setup) suggests that `pyproject.toml` replaces `MANIFEST.in`. I will fiddle around with `pyproject.toml` and see if I can get it to include the README.

**Comment by stephenfmann** [comment]
And it looks like [poetry only expects the README to appear on PyPI](https://python-poetry.org/docs/pyproject/#readme), which is currently happening correctly. So maybe everything is fine? Do we really need the README to appear in the user's `site-packages` too?

**Comment by manolomartinez** [comment]
Sorry, this can be closed now, right?

**Comment by stephenfmann** [comment]
Let me try deleting it and ensuring that it doesn't cause poetry or the PyPI upload to fail. I will assign this to me.

**Comment by stephenfmann** [comment]
Seems totally fine. I deleted `MANIFEST.in`, built with poetry, uploaded to TestPyPI, then installed in a virtual environment. Everything looks all right.

**Comment by stephenfmann** [comment]
Closed with fcbda3f4e0beaa78b557275ec7efe4fba03bb1af
