### ISSUE TITLE
Irrelevant testing

### ISSUE THREAD

**Issue by igarizio** [signalling-games-org/evoke#76]
Some tests perform irrelevant checks, for example, [this one](https://github.com/signalling-games-org/evoke/blob/9b94aa6bfb1e5a9286b35734377c6d9a1c5ea5f5/evoke/tests/test_figure.py#L54). This might boost your coverage score but, it doesn't really do much. I think it might be better if you modify them or remove them.

**Comment by stephenfmann** [comment]
OK, I've removed all the tests that were just checking `assertIsInstance`. The remaining tests should be checking substantive things, like calculations of game equilibria. Update in commit https://github.com/signalling-games-org/evoke/commit/e1e3ec0cdd7dda3000498661e6501f6d9ea19748
